namespace GCPL.Model {
    export class EditQuoteModel {
        constructor() { }
        OpportunitySAPNo: string;
        CompanyName: string;
        Address: string;
        SOAddress1: string;
        SOAddress2: string;
        SOAddress3: string;
        SOAddress4: string;
        UserName: string;
        Role: string;
        Email: string;
        PhoneNo: string;
        Subject: string;
        QuotationDate: string;
        QuotationRefernce: string;
        Quantity: string;
        Price: string;
        GSTRate: string;
        GSTAmount: string;
        TotalInvestment: string;
        StdConfig: string;
        ModelNo: string;
        Accessory1ID: number;
        Option1ID: number;
        Accessory2ID: number;
        Option2ID: number;
        Accessory3ID: number;
        Option3ID: number;
        Accessory4ID: number;
        Option4ID: number;
        Accessory5ID: number;
        Option5ID: number;
        Accessory6ID: number;
        Option6ID: number;
        TC1Heading: string;
        TC1ID: string;
        TC2Heading: string;
        TC2ID: string;
        TC3Heading: string;
        TC3ID: string;
       TC4Heading: string;
        TC4ID: string;
        TC5Heading: string;
        TC5ID: string;
        TC6Heading: string;
        TC6ID: string;
        TC7Heading: string;
        TC7ID: string;
        TC8Heading: string;
        TC8ID: string;
        PF1Heading: string;
        PF1: string;
        PF1Desc: string;
        PF1Pic: string;
        PF2Heading: string;
        PF2: string;
        PF2Desc: string;
        PF2Pic: string;
        PF3Heading: string;
        PF3: string;
        PF3Desc: string;
        PF3Pic: string;
        PF4Heading: string;
        PF4: string;
        PF4Desc: string;
        PF4Pic: string;
        PF5Heading: string;
        PF5: string;
        PF5Desc: string;
        PF5Pic: string;
        PF6Heading: string;
        PF6: string;
        PF6Desc: string;
        PF6Pic: string;
        PF7Heading: string;
        PF7: string;
        PF7Desc: string;
        PF7Pic: string;
        OF1Heading: string;
        OF1: string;
        OF1Desc: string;
        OF2Heading: string;
        OF2: string;
        OF2Desc: string;
        OF3Heading: string;
        OF3: string;
        OF3Desc: string;
        OF4Heading: string;
        OF4: string;
        OF4Desc: string;
        OF5Heading: string;
        OF5: string;
        OF5Desc: string;
        OF6Heading: string;
        OF6: string;
        OF6Desc: string;
        C1Heading: string;
        C1: string;
        C1Desc: string;
        C2Heading: string;
        C2: string;
        C2Desc: string;
        C3Heading: string;
        C3: string;
        C3Desc: string;
        C4Heading: string;
        C4: string;
        C4Desc: string;
        ModelDescription: string;
        ContactName: string;
        ModelID: string;
        C1Pic : string;
        C2Pic : string;
        C3Pic : string;
        C4Pic : string;
        OF1Pic: string;
        OF2Pic: string;
        OF3Pic: string;
        OF4Pic: string;
        OF5Pic: string;
        OF6Pic: string;
        C5Heading: string;
        C5: string;
        C5Desc: string;
        C5Pic: string;
        C6Heading: string;
        C6: string;
        C6Desc: string;
        C6Pic: string;
        TC1: string;
        TC2: string;
        TC3: string;
        TC4: string;
        TC5: string;
        TC6: string;
        TC7: string;
        TC8: string;
    }

    export class SearchEditModel {
        constructor() { }
        OpportunitySAPNo: string;
        QuotationRefernce: string;
    }

    export class EditTermsModel {
        constructor() { }
        TC1ID : string;
        TC2ID : string;
        TC3ID : string;
        TC4ID : string;
        TC5ID : string;
        TC6ID : string;
        TC7ID : string;
        TC8ID: string;
    }

    export class UpdateQuotationModel {
        constructor() {
        }

        OpportunitySAPNo: string;
        Accessory1ID: string;
        Option1ID: string;
        Accessory2ID: string;
        Option2ID: string;
        Accessory3ID: string;
        Option3ID: string;
        Accessory4ID: string;
        Option4ID: string;
        Accessory5ID: string;
        Option5ID: string;
        Accessory6ID: string;
        Option6ID: string;
        GSTRate: string;
        Price: string;
        Quantity: number;
        QuotationID: number;
        QuoteRange: string;
        TotalPrice: string;
        QuoteDate: string;
        TotalTax: string;
        UserID: number;
        TC1: string;
        TC2: string;
        TC3: string;
        TC4: string;
        TC5: string;
        TC6: string;
        TC7: string;
        TC8: string;
        PF1: string;
        PF2: string;
        PF3: string;
        PF4: string;
        PF5: string;
        PF6: string;
        PF7: string;
        Offer1: string;
        Offer2: string;
        Offer3: string;
        Offer4: string;
        Offer5: string;
        Offer6: string;
        Capability1: string;
        Capability2: string;
        Capability3: string;
        Capability4: string;
        Capability5: string;
        Capability6: string;
        ContactName: string;
        CustomerAddress: string;
        ModelID: string;
    }
}